#!/usr/bin/env python3

import rospy
import numpy as np
import open3d as o3d
import cv2
import message_filters
from sensor_msgs.msg import Image, PointCloud2, CameraInfo
from geometry_msgs.msg import Pose
from cv_bridge import CvBridge
from ultralytics import YOLO
from tf.transformations import quaternion_from_matrix
import sensor_msgs.point_cloud2 as pc2

class YoloDebugTracker:
    def __init__(self):
        rospy.init_node('yolo_cup_debugger')
        
        # 1. Config
        self.bridge = CvBridge()
        self.yolo = YOLO('src/best.pt')
        

        # 4. Publishers for DEBUGGING
        self.debug_img_pub = rospy.Publisher('/debug/yolo_image', Image, queue_size=1)
        

        # 5. Subscribers
        # Subscribe to CameraInfo to handle unorganized clouds correctly
        
        rgb_sub = rospy.Subscriber('/sciurus17/camera/color/image_raw', Image, self.callback)
        
        rospy.loginfo("Node Started. Open RViz to see /debug/yolo_image")

    def callback(self, rgb_msg):
        # --- A. YOLO DETECTION ---
        try:
            cv_image = self.bridge.imgmsg_to_cv2(rgb_msg, "bgr8")
        except: return

        # Detect Cup (Class 41)
        results = self.yolo(cv_image, classes=[0], verbose=False, conf=0.4)
        
        # DEBUG IMAGE: Draw what YOLO sees
        debug_img = cv_image.copy()
        found_cup = False
        box = None
        
        if results and results[0].boxes:
            # Take the best result
            box = results[0].boxes.xyxy[0].cpu().numpy().astype(int) # x1, y1, x2, y2
            cv2.rectangle(debug_img, (box[0], box[1]), (box[2], box[3]), (0, 255, 0), 2)
            cv2.putText(debug_img, "CUP FOUND", (box[0], box[1]-10), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0,255,0), 2)
            found_cup = True
        else:
            cv2.putText(debug_img, "NO CUP", (50, 50), cv2.FONT_HERSHEY_SIMPLEX, 1, (0,0,255), 2)

        # Publish the Debug Image immediately
        self.debug_img_pub.publish(self.bridge.cv2_to_imgmsg(debug_img, "bgr8"))

        
if __name__ == '__main__':
    try:
        YoloDebugTracker()
        rospy.spin()
    except rospy.ROSInterruptException:
        pass